name: "Kubernetes Action"
description: "Interacts with kubernetes clusters calling kubectl commands. Integrates support for AWS EKS."
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  args:
    description: "Arguments to pass to kubectl"
    required: true
outputs:
  result:
    description: "Output of the kubectl command run"
  error:
    description: "Errors emitted from the command execution"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.args }}
